TMGDATE   ;TMG/ELH-DATE FUNCTIONS ; 8/26/17
         ;;1.0;TMG-LIB;**1,17**;8/26/17
      ;  
EXTDATE(FMDATE)  ;"RETURN EXTERNAL DATE FOR PROVIDED FMDATE
      NEW Y SET Y=+$GET(FMDATE) DO DD^%DT
      QUIT Y
      ;"
INTDATE(EXTDATE) ;"RETURN FILEMAN DATE OR -1 IF INVALID FORMAT
      NEW %DT,X,Y
      SET X=EXTDATE
      DO ^%DT
      QUIT Y
      ;"
ADDDAYS(DAYS)  ;"ADD OR SUBTRACT DAYS FROM TODAY
      ;"DAYS WILL CONTAIN # OF DAYS TO ADD, OR SUBTRACT IS NEGATIVE
      NEW X,X1,X2
      SET X1=$$TODAY(),X2=+$GET(DAYS)
      DO C^%DTC
      QUIT X 
      ;"
NOW() ;"RETURNS THE TIME RIGHT NOW
      NEW X DO NOW^%DTC
      QUIT $P(%,".",2)
      ;"
TODAY(EXTERNAL,FORMAT)  ;"RETURNS TODAY'S DATE
      ;"EXTERNAL (0 OR 1): IF 0 (DEFAULT), THE FILEMAN VALUE WILL BE RETURNED, ELSE THE FM DATE
      ;"FORMAT (0 OR 1): ONLY USES IF EXTERNAL=1, IF 0 (DEFAULT) MONTH
      ;"        DAY,YEAR. IF 1 MM/DD/YYYY
      NEW X
      SET EXTERNAL=+$G(EXTERNAL)
      SET FORMAT=+$G(FORMAT)
      DO NOW^%DTC
      IF EXTERNAL=1 DO
      . IF FORMAT=1 DO
      . . SET X=$$FMTE^XLFDT(X,"2D")
      . ELSE  DO
      . . SET X=$$EXTDATE(X)
      QUIT X
      ;"   
MNTHNAME(FMDATE)  ;"RETURNS DEC. 2017
      NEW MONTHS 
      SET MONTHS="JAN^FEB^MAR^APR^MAY^JUN^JUL^AUG^SEPT^OCT^NOV^DEC"
      NEW MONTH,YEAR
      SET MONTH=$E(FMDATE,4,5)
      SET YEAR=$E(FMDATE,1,3)+1700
      QUIT $P(MONTHS,"^",MONTH)_". "_YEAR
      ;"
FIRSTYR()  ;"FIRST DAY OF THE YEAR
      NEW DATE
      SET DATE=$$TODAY
      SET DATE=$E(DATE,1,3)_"0101.000000"
      QUIT DATE
      ;"
DAYSDIFF(DATE1,DATE2)  ;"RETURNS THE DIFFERENCE BETWEEN 2 DTS IN DAYS
      NEW X,X1,X2
      SET X1=DATE1,X2=DATE2
      DO ^%DTC
      IF X["-" SET X=$P(X,"-",2)
      QUIT X
      ;"
TIMEDIFF(DATE1,DATE2)  ;"RETURNS THE DIFFERENCE BETWEEN 2 DTS IN MINUTES
      NEW DAYSDIFF SET DAYSDIFF=$$DAYSDIFF(DATE1,DATE2)
      SET DATE1=$P(DATE1,".",2),DATE2=$P(DATE2,".",2)
      NEW HOURS,MINUTES,H1,H2,M1,M2
      SET H1=$E(DATE1,1,2),M1=$E(DATE1,3,4)
      SET H2=$E(DATE2,1,2),M2=$E(DATE2,3,4)
      SET HOURS=((H1-H2)*60)
      IF HOURS["-" SET HOURS=$P(HOURS,"-",2)
      SET MINUTES=M1-M2
      IF MINUTES["-" SET MINUTES=$P(MINUTES,"-",2)
      SET MINUTES=MINUTES+(DAYSDIFF*1440)      
      QUIT MINUTES
      ;"