TMGDATE   ;TMG/ELH-DATE FUNCTIONS ; 8/26/17
         ;;1.0;TMG-LIB;**1,17**;8/26/17
      ;  
EXTDATE(FMDATE)  ;"RETURN EXTERNAL DATE FOR PROVIDED FMDATE
      NEW Y SET Y=+$GET(FMDATE) DO DD^%DT
      QUIT Y
      ;"
ADDDAYS(DAYS)  ;"ADD OR SUBTRACT DAYS FROM TODAY
      ;"DAYS WILL CONTAIN # OF DAYS TO ADD, OR SUBTRACT IS NEGATIVE
      NEW X,X1,X2
      SET X1=$$TODAY(),X2=+$GET(DAYS)
      DO C^%DTC
      QUIT X 
      ;"
TODAY(EXTERNAL)  ;"RETURNS TODAY'S DATE
      ;"EXTERNAL (0 OR 1)
      ;" IF 0 (DEFAULT), THE FILEMAN VALUE WILL BE RETURNED, ELSE THE FM DATE
      NEW X
      SET EXTERNAL=+$G(EXTERNAL)
      DO NOW^%DTC
      IF EXTERNAL=1 SET X=$$EXTDATE(X)
      QUIT X
      ;"   