TMGIMPRT  ;"

IMPPAYAVG
  ;"IMPORT PAYMENT DATA FROM SEQUEL AND STORE AVERAGE PAYMENTS INTO VISTA
  ;"plan_short_name,visit_date_from,proc_cpt_code,practice_name,location_name,provider_name,total_amount_charged,total_amount_paid,total_adjustment,icd_9_code,modifier,visit_seq_num,charge_seq_num,patient_seq_num,parent_seq_num,ref_provider,mhrvs
  ;"PARSE CSV FROM SEQUEL
  NEW ARRAY,OPTION,OUTARR
  NEW IDX SET IDX=1
  NEW INSARRAY
  NEW PLAN,PAID,CPT,VISIT
  NEW DATE SET DATE=$$TODAY^TMGDATE
  DO HFS2ARR^TMGIOUT3("/mnt/WinServer","TEST2.csv","ARRAY",.OPTION)
  FOR  SET IDX=$O(ARRAY(IDX)) QUIT:IDX'>0  DO
  . NEW LINE SET LINE=$G(ARRAY(IDX))
  . SET PLAN=$P(LINE,",",1),PAID=$P(LINE,",",8),CPT=$P(LINE,",",3),VISIT=$P(LINE,",",12)
  . IF PAID["." SET PAID=+$P(PAID,".",1)
  . IF PAID'>0 QUIT
  . SET INSARRAY(PLAN,CPT,VISIT)=PAID
  SET PLAN=""
  ;"CALCULATE AVERAGES AND STORE
  NEW TMGFDA,TMGIEN,TMGMSG,TMGIENS
  FOR  SET PLAN=$O(INSARRAY(PLAN)) QUIT:PLAN=""  DO
  . WRITE "GOING THROUGH PLAN ",PLAN,!
  . NEW PLANIEN SET PLANIEN=+$O(^DIC(36,"C",PLAN,0))
  . ;"IF PLANIEN'>0 SET PLANIEN=+$O(^DIC(36,"B",PLAN_" (EDIT THIS NAME)",0))
  . IF PLANIEN'>0 WRITE "CANNOT FIND ",PLAN,! QUIT
  . ;"SAVE TODAY'S DATE IN PLAN
  . K TMGIENS,TMGFDA,TMGMSG
  . SET TMGIENS="+1,"_PLANIEN_","
  . SET TMGFDA(36.01,TMGIENS,.01)=DATE
  . DO UPDATE^DIE("","TMGFDA","TMGIENS","TMGMSG")
  . IF $D(TMGMSG("DIERR")) QUIT
  . NEW DATEIEN SET DATEIEN=+$G(TMGIENS(1))
  . ;"IF DATEIEN'>0 WRITE "NO DATE CAN BE STORED",! QUIT
  . SET CPT=0
  . FOR  SET CPT=$O(INSARRAY(PLAN,CPT)) QUIT:CPT'>0  DO
  . . WRITE "    ->",CPT
  . . SET VISIT=0
  . . NEW TOTCPTS,TOTPAID,HIGH,LOW
  . . SET (TOTCPTS,TOTPAID,HIGH)=0,LOW=999
  . . FOR  SET VISIT=$O(INSARRAY(PLAN,CPT,VISIT)) QUIT:VISIT'>0  DO
  . . . SET PAID=$G(INSARRAY(PLAN,CPT,VISIT))
  . . . IF PAID>HIGH SET HIGH=PAID
  . . . IF PAID<LOW SET LOW=PAID
  . . . SET TOTCPTS=TOTCPTS+1
  . . . SET TOTPAID=TOTPAID+PAID
  . . NEW AVERAGE SET AVERAGE=TOTPAID/TOTCPTS
  . . SET AVERAGE=$J(AVERAGE,0,2)
  . . WRITE " ",AVERAGE,!
  . . ;"SET OUTARR(PLAN,CPT)=AVERAGE
  . . WRITE PLAN,"-",CPT,"-",AVERAGE,"-",HIGH,"-",LOW,!
  . . K TMGIENS,TMGFDA,TMGMSG
  . . SET TMGIENS="+1,"_DATEIEN_","_PLANIEN_","
  . . SET TMGFDA(36.11,TMGIENS,.01)=CPT
  . . SET TMGFDA(36.11,TMGIENS,1)=AVERAGE
  . . SET TMGFDA(36.11,TMGIENS,1.1)=HIGH
  . . SET TMGFDA(36.11,TMGIENS,1.2)=LOW
  . . DO UPDATE^DIE("","TMGFDA","TMGIENS","TMGMSG")
  . . IF $DATA(TMGMSG("DIERR")) DO
  . . . WRITE $$GETERSTR^TMGRPC3G(.TMGMSG),!
  QUIT
  ;"