TMGORWD1 ;TMG/kst/ExtraOrderPrint functions 9/1/2022
         ;;1.0;TMG-LIB;**1**;09/01/2022
CHK4FAX(PRTLIST)
    NEW TMGTEST SET TMGTEST=0
    IF TMGTEST=1 DO
    . MERGE PRTLIST=^TMG("TMGORWD1")
    ELSE  DO
    . MERGE ^TMG("TMGORWD1")=PRTLIST
    NEW I
    SET I=0
    FOR  SET I=$O(PRTLIST(I)) QUIT:I'>0  DO
    . NEW ORDIEN SET ORDIEN=+$G(PRTLIST(I))
    . IF ORDIEN'>0 QUIT
    . NEW ORDERARR
    . DO TEXT^ORQ12(.ORDERARR,ORDIEN,"")
    . NEW LINEIDX SET LINEIDX=0
    . NEW ORDERTEXT SET ORDERTEXT=""
    . FOR  SET LINEIDX=$O(ORDERARR(LINEIDX)) QUIT:LINEIDX'>0  DO
    . . SET ORDERTEXT=ORDERTEXT_$$UP^XLFSTR(ORDERARR(LINEIDX))
    . IF ORDERTEXT["FAX" DO
    . . NEW TMGDFN SET TMGDFN=+$P($G(^OR(100,ORDIEN,0)),"^",2)
    . . NEW MSG SET MSG=$P($G(^DPT(TMGDFN,0)),"^",1)_" HAD A LAB ORDER PRINTED THAT NEEDS TO BE FAXED"
    . . NEW ALRTMSG DO INFRMALT^TMGXQAL(.ALRTMSG,150,MSG)    
    QUIT
    ;"
