TMGRPC1H ;TMG/kst-RPC Functions ;5/1/13, 2/2/14, 3/24/21
         ;;1.0;TMG-LIB;**1**;5/1/13
 ;
 ;"TMG RPC FUNCTIONS especially related to CPRS
 ;"  Process Note (note sent from CPRS for extra processing, then returned)
 ;
 ;"~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--
 ;"Copyright (c) 6/23/2015  Kevin S. Toppenberg MD
 ;"
 ;"This file is part of the TMG LIBRARY, and may only be used in accordence
 ;" to license terms outlined in separate file TMGLICNS.m, which should 
 ;" always be distributed with this file.
 ;"~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--
 ;
 ;"=======================================================================
 ;" RPC -- Public Functions.
 ;"=======================================================================
 ;"PROCESS(TMGRESULT,TMGIN) -- Entrypoint for RPC to effect processing a note from CPRS
 ;"
 ;"=======================================================================
 ;"Dependancies:
 ;" TMGHTM1, TMGTIUOJ, TMGTIUO6, XLFSTR, TMGSTUT2, TMGSTUT3
 ;"=======================================================================
 ;
PROCESS(TMGRESULT,TMGIN,FORCE) ;"Entry point for RPC: TMG CPRS PROCESS NOTE
  ;"Input:  TMGRESULT -- output value
  ;"        TMGIN -- Input from client.  Format:
  ;"          TMGIN("DFN")=<DFN>  (IEN in PATIENT file)
  ;"          TMGIN("NoteIEN")=<TIUIEN>
  ;"          TMGIN("TEXT",1) = 1st line of text
  ;"          TMGIN("TEXT",2) = 2nd line of text, etc
  ;"        FORCE -- Optional. If 1,  note is processed even if tag is absent. Default is 0.
  ;"            UPDATE NOTE: we are forcing this to 1 below, regardless of RPC input
  NEW TMGZZDEBUG SET TMGZZDEBUG=0
  IF TMGZZDEBUG DO
  . KILL TMGIN,FORCE
  . MERGE TMGIN=^TMG("TMP","PROCESS^TMGRPC1H","TMGIN")
  . MERGE FORCE=^TMG("TMP","PROCESS^TMGRPC1H","FORCE")
  ELSE  DO
  . KILL ^TMG("TMP","PROCESS^TMGRPC1H")
  . MERGE ^TMG("TMP","PROCESS^TMGRPC1H","TMGIN")=TMGIN
  . MERGE ^TMG("TMP","PROCESS^TMGRPC1H","FORCE")=FORCE
  NEW OPTION 
  SET OPTION("ALL NOTES")=1
  SET FORCE=1 ;"ELH  Always process note  //kt moved from PROCESS^TMGTIUP3 to here 5/20/18  
  SET OPTION("FORCE PROCESS")=$GET(FORCE)  
  NEW USENEWMETHOD SET USENEWMETHOD=1
  IF USENEWMETHOD DO
  . DO SAVAMED^TMGTIUP3(.TMGIN)  ;"Move MEDICATION table to FINAL MEDICATION table
  . SET OPTION("FORCE REFRESH TABLE","FINAL MEDICATIONS")=1
  ELSE  DO
  . DO MOVEMEDS^TMGTIUP3(.TMGIN)  ;"Move MEDICATION table to FINAL MEDICATION table
  SET OPTION("DIRECT HTML INSERTION")=1  ;"//kt 5/23/18
  DO PROCESS^TMGTIUP3(.TMGRESULT,.TMGIN,.OPTION) ;
  QUIT
  ;
MOVEMEDS(TMGIN)  ;"Used as part of the RPC: TMG CPRS PROCESS NOTE  -- depreciated (see above)
  ;"Purpose: This function replaces the FINAL MEDICATION table with the
  ;"         MEDICATION table found within the note.
  ;"Input:   TMGIN -- Input from client.  Format:
  ;"              TMGIN("DFN")=<DFN>  (IEN in PATIENT file)
  ;"              TMGIN("NoteIEN")=<TIUIEN>
  ;"              TMGIN("TEXT",1) = 1st line of text
  ;"              TMGIN("TEXT",2) = 2nd line of text, etc
  ;"Output: TMGIN will contain the text as sent, with changes
  ;"Result: none
  NEW IDX,TEMPNOTE,TEMPIDX,MEDARR,MEDIDX,FOUNDMED,ENDFOUND,PARTB
  SET (IDX,TEMPIDX,MEDIDX,FOUNDMED)=0
  NEW FOUNDFINAL SET FOUNDFINAL=0
  FOR  SET IDX=$ORDER(TMGIN("TEXT",IDX)) QUIT:IDX'>0  DO
  . NEW LINE SET LINE=$G(TMGIN("TEXT",IDX))
  . IF FOUNDMED=1 DO
  . . IF LINE["<P>" SET FOUNDMED=0
  . . ELSE  DO
  . . . SET MEDIDX=MEDIDX+1
  . . . SET MEDARR(MEDIDX)=LINE
  . IF LINE["[MEDICATION" SET FOUNDMED=1
  . ;"
  . ELSE  DO
  . . IF LINE["<P>" SET FOUNDFINAL=0
  . IF FOUNDFINAL'=1 DO 
  . . SET TEMPIDX=TEMPIDX+1
  . . SET TEMPNOTE(TEMPIDX)=LINE
  . IF LINE["[FINAL MED" DO
  . . SET FOUNDFINAL=1
  . . SET MEDIDX=0
  . . FOR  SET MEDIDX=$ORDER(MEDARR(MEDIDX)) QUIT:MEDIDX'>0  DO
  . . . SET TEMPIDX=TEMPIDX+1
  . . . SET TEMPNOTE(TEMPIDX)=$G(MEDARR(MEDIDX))
  KILL TMGIN("TEXT")
  MERGE TMGIN("TEXT")=TEMPNOTE
  NEW TMGDFN SET TMGDFN=$G(TMGIN("DFN"))
  ;"NOW THAT MEDS ARE MOVED... STORE THE MEDARR INTO GLOBAL, SO THAT
  ;"      REFRESH TABLES WILL USE IT.
  NEW STORENAME SET STORENAME="MEDICATIONS TABLE-"_TMGDFN
  NEW REF SET REF=$$GETMPREF^TMGMISC2(STORENAME)
  NEW PRIORTIME SET PRIORTIME=+$GET(@REF@("D","HTIME"))
  NEW DELTASEC SET DELTASEC=$$HDIFF^XLFDT($H,PRIORTIME,2)  ;"returns seconds
  NEW ARR,H SET H=$H MERGE ARR("HTIME")=H
  ;"ARRANGE MEDARR INTO PROPER FORMAT
  NEW TMPMEDARR,IDX,TMPIDX
  SET IDX=0,TMPIDX=1       
  FOR  SET IDX=$O(MEDARR(IDX)) QUIT:IDX'>0  DO
  . IF $E($G(MEDARR(IDX)))="*" DO
  . . NEW P1,P2,VALUE
  . . SET VALUE=$G(MEDARR(IDX))
  . . SET P1=$P(VALUE," = ",1),P2=$P(VALUE," = ",2)
  . . SET TMPMEDARR("KEY-VALUE",P1)=P2
  . . SET TMPMEDARR("KEY-VALUE",P1,"LINE")=VALUE
  . ELSE  DO
  . . SET TMPMEDARR(TMPIDX)=$G(MEDARR(IDX))
  . . SET TMPIDX=TMPIDX+1
  SET TMPMEDARR("KEY-VALUE","SOURCE-DATE")=$$NOW^XLFDT()
  MERGE ARR("TABLE")=TMPMEDARR
  DO TMPSAVE^TMGMISC2(.ARR,STORENAME,"5M")
  QUIT
  ;
NOTETOC(TMGRESULT,TMGIN)  ;"ENTRY POINT FOR RPC: TMG CPRS GET NOTE TOC
  NEW TMGZZDEBUG SET TMGZZDEBUG=0
  IF TMGZZDEBUG DO
  . KILL TMGIN,FORCE
  . MERGE TMGIN=^TMG("TMP","NOTETOC^TMGRPC1H","TMGIN")
  ELSE  DO
  . KILL ^TMG("TMP","NOTETOC^TMGRPC1H")
  . MERGE ^TMG("TMP","NOTETOC^TMGRPC1H","TMGIN")=TMGIN
  ;"DO TOCTEST(.TMGRESULT)
  K TMGRESULT,TMGOUT
  SET TMGRESULT(0)="1^SUCCESS"
  NEW OUTIDX SET OUTIDX=1
  DO TOCHEAD(.TMGRESULT,.OUTIDX)
  DO TOCPARSE(.TMGRESULT,.OUTIDX,.TMGIN)
  DO TOCFOOT(.TMGRESULT,.OUTIDX)
  QUIT
  ;"
ADDCSS()  
  QUIT
  ;"
TOCHEAD(TMGOUT,OUTIDX)  
  SET TMGOUT(OUTIDX)="<!DOCTYPE html>",OUTIDX=OUTIDX+1
  SET TMGOUT(OUTIDX)="<html lang=""en"">",OUTIDX=OUTIDX+1
  SET TMGOUT(OUTIDX)="<head>",OUTIDX=OUTIDX+1
  SET TMGOUT(OUTIDX)="<meta charset=""UTF-8"">",OUTIDX=OUTIDX+1
  SET TMGOUT(OUTIDX)="<meta name=""viewport"" content=""width=device-width, initial-scale=1.0"">",OUTIDX=OUTIDX+1
  SET TMGOUT(OUTIDX)="<title>Static HTML Treeview with Ordered Lists</title>",OUTIDX=OUTIDX+1
  ;"  
  SET TMGOUT(OUTIDX)="<style>",OUTIDX=OUTIDX+1
  SET TMGOUT(OUTIDX)="",OUTIDX=OUTIDX+1
  SET TMGOUT(OUTIDX)="",OUTIDX=OUTIDX+1  
  SET TMGOUT(OUTIDX)="",OUTIDX=OUTIDX+1
  SET TMGOUT(OUTIDX)="ul {",OUTIDX=OUTIDX+1
    SET TMGOUT(OUTIDX)="background: #ffffe6;",OUTIDX=OUTIDX+1
  SET TMGOUT(OUTIDX)="",OUTIDX=OUTIDX+1 
           SET TMGOUT(OUTIDX)="color: green;",OUTIDX=OUTIDX+1
           SET TMGOUT(OUTIDX)="padding: 10px;",OUTIDX=OUTIDX+1
  SET TMGOUT(OUTIDX)="",OUTIDX=OUTIDX+1
           SET TMGOUT(OUTIDX)="margin: 1px;",OUTIDX=OUTIDX+1
           SET TMGOUT(OUTIDX)="margin-top: 0px;",OUTIDX=OUTIDX+1
           SET TMGOUT(OUTIDX)="margin-left: 5px;",OUTIDX=OUTIDX+1
           SET TMGOUT(OUTIDX)="margin-right: 0px;",OUTIDX=OUTIDX+1
           SET TMGOUT(OUTIDX)="border: none;",OUTIDX=OUTIDX+1
         SET TMGOUT(OUTIDX)="}",OUTIDX=OUTIDX+1
  SET TMGOUT(OUTIDX)="",OUTIDX=OUTIDX+1 
  SET TMGOUT(OUTIDX)="",OUTIDX=OUTIDX+1
  SET TMGOUT(OUTIDX)="ul li {",OUTIDX=OUTIDX+1
    SET TMGOUT(OUTIDX)="background: #ffffe6;",OUTIDX=OUTIDX+1
  SET TMGOUT(OUTIDX)="",OUTIDX=OUTIDX+1 
              SET TMGOUT(OUTIDX)="color: darkred;",OUTIDX=OUTIDX+1
  SET TMGOUT(OUTIDX)="",OUTIDX=OUTIDX+1  
              SET TMGOUT(OUTIDX)="margin: 1px;",OUTIDX=OUTIDX+1
  SET TMGOUT(OUTIDX)="",OUTIDX=OUTIDX+1
              SET TMGOUT(OUTIDX)="margin-right: 0px;",OUTIDX=OUTIDX+1
             SET TMGOUT(OUTIDX)="margin-top: 0px;",OUTIDX=OUTIDX+1
             SET TMGOUT(OUTIDX)="margin-bottom: 0px;",OUTIDX=OUTIDX+1
            SET TMGOUT(OUTIDX)="}",OUTIDX=OUTIDX+1
  SET TMGOUT(OUTIDX)="",OUTIDX=OUTIDX+1
  SET TMGOUT(OUTIDX)="</style>",OUTIDX=OUTIDX+1
  SET TMGOUT(OUTIDX)="",OUTIDX=OUTIDX+1
  SET TMGOUT(OUTIDX)="",OUTIDX=OUTIDX+1
  SET TMGOUT(OUTIDX)="</head>",OUTIDX=OUTIDX+1
  SET TMGOUT(OUTIDX)="<body style=""font-family:'Georgia';"">",OUTIDX=OUTIDX+1
  SET TMGOUT(OUTIDX)="",OUTIDX=OUTIDX+1
  SET TMGOUT(OUTIDX)="<h2>NOTE CONTENTS</h2>",OUTIDX=OUTIDX+1
  SET TMGOUT(OUTIDX)="<ul id=""myUL"">",OUTIDX=OUTIDX+1
  QUIT
  ;"
TOCPARSE(TMGOUT,OUTIDX,TMGIN)
  ;OLD CODE AT BOTTOM OF ROUTINE IF I MESSED SOMETHING UP
  NEW TMGHPI SET TMGHPI=""    
  ;"CONVERT ENTIRE NOTE INTO LONG STRING (TMGHPI)
  SET IDX=0 FOR  SET IDX=$ORDER(TMGIN("TEXT",IDX)) QUIT:IDX'>0  DO
  . SET TMGHPI=TMGHPI_$GET(TMGIN("TEXT",IDX))
  IF TMGHPI="" SET TMGRESULT="-1^No text for not found for processing." QUIT         
  NEW SECTIONARR,TOPICTAG
  SET SECTIONARR("HISTORY OF PRESENT ILLNESS (HPI)")=""
  SET SECTIONARR("PAST MEDICAL HISTORY (PMH)")=""
  SET SECTIONARR("PHYSICAL EXAM (PE)")=""
  SET SECTIONARR("REVIEW OF SYSTEMS")=""
  SET SECTIONARR("ASSESSMENT &amp; PLAN")=""
  SET SECTIONARR("FOLLOW UP APPT:")=""
  NEW STARTDIV,ENDDIV SET (STARTDIV,ENDDIV)=""
  ;"
  SET TMGHPI=$$UPTAGS^TMGHTM2(TMGHPI)  ;"force all tags to UPPER CASE
  ;"Remove/replace unwanted tags / strings from note  
  DO RPTAGS^TMGHTM1(.TMGHPI,"<BR />","<BR>")
  DO RPTAGS^TMGHTM1(.TMGHPI,"<P />","<P>")
  DO RMTAGS^TMGHTM1(.TMGHPI,"=== HPI ISSUES BELOW WERE NOT ADDRESSED TODAY ===")
  DO RMTAGS^TMGHTM1(.TMGHPI,"--&nbsp;[FOLLOWUP&nbsp;ITEMS]&nbsp;---------")
  ;"DO RMTAGS^TMGHTM1(.TMGHPI,"-- [FOLLOWUP ITEMS] ---------")
  DO RPTAGS^TMGHTM1(.TMGHPI,"<LI>  <P>","<LI> ")
  DO RPTAGS^TMGHTM1(.TMGHPI,"[group ","[GROUP ")  ;"force group tags to be ucase 11/13/18
  DO RPTAGS^TMGHTM1(.TMGHPI,"[Group ","[GROUP ")
  DO RMTAGS^TMGHTM1(.TMGHPI,"<I>")   ;"//kt should have been already removed via DOM processing
  DO RMTAGS^TMGHTM1(.TMGHPI,"<EM>")  ;"//kt should have been already removed via DOM processing
  DO RMTAGS^TMGHTM1(.TMGHPI,"</I>")  ;"//kt should have been already removed via DOM processing
  DO RMTAGS^TMGHTM1(.TMGHPI,"</EM>") ;"//kt should have been already removed via DOM processing         
  ;"                           
  ;"Parse Items
  NEW TABLES,SECTION SET IDX=1 
  NEW OUTSIDEHPI SET OUTSIDEHPI=1
  NEW INSIDESECTION SET INSIDESECTION=0
  NEW INSIDETOPIC SET INSIDETOPIC=0
  NEW TOPICOL SET TOPICOL=0
  NEW DELIMITER SET DELIMITER=$$NEXTCH^TMGSTUT3(TMGHPI,0,"<LI>","*")
  ;"If the delimiter is *, then we will replace any <LI>'s to *
  ;"IF DELIMITER="*" SET TMGHPI=$$REPLSTR^TMGSTUT3(TMGHPI,"<LI>","*")
  ;"
  ;"NEW INSIDE
  NEW DELIMITER
  NEW TABLEARR
  NEW TOCARR,CURSECTION   ;"CHANGING THE WAY WE SAVE OFF THE DATA. INSTEAD OF SAVING THE DATA AS WE GO, I AM GOING TO STORE THE DATA LIKE THIS: TOCARR(SECTION,TITLE) AND THEN HAVE ONE FUNCTION THAT SETS THE LIST AFTERWARDS
  SET CURSECTION=""
  NEW HPIARR,HPIIDX
  SET HPIIDX=1
  NEW HPIALPHA SET HPIALPHA=1   ;"CHANGE THIS (PER USER OR SETTING) IF YOU DON'T WANT ALPHABETICAL
  FOR  QUIT:TMGHPI=""  DO
  . ;"ADD FOLLOWUP AT BOTTOM TO THE LIST
  . IF OUTSIDEHPI DO
  . . SET DELIMITER=$$NEXTCH^TMGSTUT3(TMGHPI,0,"-- [","HISTORY OF PRESENT ILLNESS (HPI)","PAST MEDICAL HISTORY (PMH)","PHYSICAL EXAM (PE)","REVIEW OF SYSTEMS","ASSESSMENT &amp; PLAN","FOLLOW UP APPT:") 
  . ELSE  DO
  . . SET DELIMITER=$$NEXTCH^TMGSTUT3(TMGHPI,0,"*","<LI>","-- [","HISTORY OF PRESENT ILLNESS (HPI)","PAST MEDICAL HISTORY (PMH)","PHYSICAL EXAM (PE)","REVIEW OF SYSTEMS","ASSESSMENT &amp; PLAN","FOLLOW UP APPT:")
  . NEW TOPIC
  . IF DELIMITER="-- [" DO
  . . SET TOPIC=$P(TMGHPI,DELIMITER,2)
  . . SET TOPIC=$P(TOPIC,"] --",1)
  . . SET TMGHPI=$P(TMGHPI,"] --",2,999)
  . . SET TOCARR("ZTABLES",TOPIC)=""
  . ELSE  IF $D(SECTIONARR(DELIMITER)) DO
  . . IF DELIMITER["HPI" DO
  . . . SET OUTSIDEHPI=0
  . . ELSE  DO
  . . . SET OUTSIDEHPI=1
  . . IF DELIMITER["HPI" DO
  . . . SET CURSECTION="A"_DELIMITER
  . . ELSE  DO
  . . . SET CURSECTION=DELIMITER
  . . SET TOCARR(CURSECTION)=""
  . . SET TMGHPI=$P(TMGHPI,DELIMITER,2,999)
  . . SET INSIDETOPIC=0
  . ELSE  DO
  . . SET TMGHPI=$PIECE(TMGHPI,DELIMITER,2,999)
  . . NEW NEXTDEL
  . . IF OUTSIDEHPI DO
  . . . SET NEXTDEL=$$NEXTCH^TMGSTUT3(TMGHPI,0,"-- [","HISTORY OF PRESENT ILLNESS (HPI):","PAST MEDICAL HISTORY (PMH)","PHYSICAL EXAM (PE)","REVIEW OF SYSTEMS","ASSESSMENT &amp; PLAN","FOLLOW UP APPT:") 
  . . ELSE  DO
  . . . SET NEXTDEL=$$NEXTCH^TMGSTUT3(TMGHPI,0,"*","<LI>","-- [","HISTORY OF PRESENT ILLNESS (HPI):","PAST MEDICAL HISTORY (PMH)","PHYSICAL EXAM (PE)","REVIEW OF SYSTEMS","ASSESSMENT &amp; PLAN","FOLLOW UP APPT:")
  . . NEW SECTION SET SECTION=$PIECE(TMGHPI,NEXTDEL,1)
  . . NEW TITLE,TEXTARR DO SPLITTL^TMGTIUP2(SECTION,.TITLE,.TEXTARR,.TABLES,.OPTION) ;"Parse to a title of section, and parts
  . . DO RMTAGS^TMGHTM1(.TITLE,$C(13,10,13,10))  ;"//kt should have been already removed via DOM processing
  . . DO RMTAGS^TMGHTM1(.TITLE,$C(13,10))  ;"//kt should have been already removed via DOM processing
  . . NEW TRIMTITLE SET TRIMTITLE=$$TRIM^XLFSTR(TITLE)
  . . SET INSIDETOPIC=1,TOPICOL=0
  . . IF CURSECTION="" SET CURSECTION="NO SECTION FOUND"
  . . IF TRIMTITLE'="" DO
  . . . IF $D(TOCARR(CURSECTION,TITLE)) SET TITLE=TITLE_" (DUPLICATE)"  ;"6/18/24
  . . . SET TOCARR(CURSECTION,TITLE)=""
  . . . IF CURSECTION["HPI" SET HPIARR(HPIIDX)=TITLE,HPIIDX=HPIIDX+1
  ;"
  NEW SECTION,TITLE SET SECTION=""
  FOR  SET SECTION=$O(TOCARR(SECTION)) QUIT:SECTION=""  DO
  . IF SECTION="ZTABLES" DO
  . . SET TMGOUT(OUTIDX)="<ul>",OUTIDX=OUTIDX+1
  . . SET TMGOUT(OUTIDX)="<li>TABLES</li>",OUTIDX=OUTIDX+1
  . ELSE  IF SECTION["HPI" DO
  . . SET TMGOUT(OUTIDX)="<ul>",OUTIDX=OUTIDX+1
  . . SET TMGOUT(OUTIDX)="<li><a href=""HISTORY OF PRESENT ILLNESS (HPI):"">HISTORY OF PRESENT ILLNESS (HPI):</a></li>",OUTIDX=OUTIDX+1
  . ELSE  DO
  . . SET TMGOUT(OUTIDX)="<ul>",OUTIDX=OUTIDX+1
  . . SET TMGOUT(OUTIDX)="<li><a href="""_SECTION_""">"_SECTION_"</a></li>",OUTIDX=OUTIDX+1
  . SET TITLE=""
  . NEW SUBITEMS SET SUBITEMS=0
  . IF (SECTION["HPI")&(HPIALPHA=0) DO   ;"DO THIS BY ORDER IN NOTE, DEFAULT IS ALPHABETICAL
  . . SET HPIIDX=0
  . . FOR  SET HPIIDX=$O(HPIARR(HPIIDX)) QUIT:HPIIDX'>0  DO
  . . . IF SUBITEMS=0 DO
  . . . . SET TMGOUT(OUTIDX)="<ul>",OUTIDX=OUTIDX+1
  . . . . SET SUBITEMS=1
  . . . NEW HPITITLE SET HPITITLE=$G(HPIARR(HPIIDX))
  . . . SET TMGOUT(OUTIDX)="<li><a href="""_HPITITLE_":"">"_HPITITLE_"</a></li>",OUTIDX=OUTIDX+1
  . ELSE  DO
  . . FOR  SET TITLE=$O(TOCARR(SECTION,TITLE)) QUIT:TITLE=""  DO
  . . . IF SUBITEMS=0 DO
  . . . . SET TMGOUT(OUTIDX)="<ul>",OUTIDX=OUTIDX+1
  . . . . SET SUBITEMS=1
  . . . IF SECTION="ZTABLES" DO
  . . . . SET TMGOUT(OUTIDX)="<li><a href=""["_TITLE_"]"">"_TITLE_" table</a></li>",OUTIDX=OUTIDX+1
  . . . ELSE  DO
  . . . . SET TMGOUT(OUTIDX)="<li><a href="""_TITLE_":"">"_TITLE_"</a></li>",OUTIDX=OUTIDX+1
  . IF SUBITEMS=1 SET TMGOUT(OUTIDX)="</ul>",OUTIDX=OUTIDX+1
  . SET TMGOUT(OUTIDX)="</ul>",OUTIDX=OUTIDX+1
  ;"
  QUIT
  ;"
INSRTHPI(TMGOUT,OUTIDX,HPIARR)
  NEW TITLE SET TITLE=""
  FOR  SET TITLE=$O(HPIARR(TITLE)) QUIT:TITLE=""  DO
  . SET TMGOUT(OUTIDX)="<li><a href="""_TITLE_":"">"_TITLE_"</a></li>",OUTIDX=OUTIDX+1
  QUIT
  ;"
TOCFOOT(TMGOUT,OUTIDX,TMGIN)
  SET TMGOUT(OUTIDX)="",OUTIDX=OUTIDX+1
  SET TMGOUT(OUTIDX)="</body>",OUTIDX=OUTIDX+1
  SET TMGOUT(OUTIDX)="</html>",OUTIDX=OUTIDX+1
  QUIT
  ;"
TOCTEST(TMGIN)
;"OLD CODE
         NEW LINEIDX SET LINEIDX=9999999
            FOR  SET LINEIDX=$ORDER(TMGIN("TEXT",LINEIDX)) QUIT:LINEIDX'>0  DO
            . NEW LINE SET LINE=$G(TMGIN("TEXT",LINEIDX))
  . NEW TOPIC,TABLE,TEXT
  . IF LINE["--[" DO    ;"Look for tables first
  . . SET TABLE=$P(LINE,"-- [",2)
  . . SET TABLE=$P(LINE,"]",1)
  . . SET TMGOUT(OUTIDX)="<li><a href=""["_TABLE_"]"">"_TABLE_" table</a></li>",OUTIDX=OUTIDX+1
  . . SET TOPIC=$P(LINE,":",1)
  . . SET TOPIC=$$STRIPTAG^TMGHTM1(TOPIC)
  . . SET TOPIC=$$HTML2TXS^TMGHTM1(TOPIC)  ;"//kt 2/26/23
  . . SET TOPIC=$$TRIM^XLFSTR(TOPIC)
  . . SET TMGOUT(OUTIDX)="<li><a href="""_TOPIC_""">"_TOPIC_"</a></li>",OUTIDX=OUTIDX+1
  
  ;"TEST CODE
  NEW OUTIDX SET OUTIDX=1
  SET TMGIN(0)="1^SUCCESS"
  SET TMGIN(OUTIDX)="<!DOCTYPE html>",OUTIDX=OUTIDX+1
  SET TMGIN(OUTIDX)="<html lang=""en"">",OUTIDX=OUTIDX+1
  SET TMGIN(OUTIDX)="<head>",OUTIDX=OUTIDX+1
      SET TMGIN(OUTIDX)="<meta charset=""UTF-8"">",OUTIDX=OUTIDX+1
      SET TMGIN(OUTIDX)="<meta name=""viewport"" content=""width=device-width, initial-scale=1.0"">",OUTIDX=OUTIDX+1
      SET TMGIN(OUTIDX)="<title>Static HTML Treeview with Ordered Lists</title>",OUTIDX=OUTIDX+1
  SET TMGIN(OUTIDX)="</head>",OUTIDX=OUTIDX+1
  SET TMGIN(OUTIDX)="<body>",OUTIDX=OUTIDX+1
  SET TMGIN(OUTIDX)="",OUTIDX=OUTIDX+1
  SET TMGIN(OUTIDX)="<h2>NOTE CONTENTS TREE VIEW</h2>",OUTIDX=OUTIDX+1
  SET TMGIN(OUTIDX)="<ol id=""myUL"">",OUTIDX=OUTIDX+1
    SET TMGIN(OUTIDX)="<li>Note Contents",OUTIDX=OUTIDX+1
      SET TMGIN(OUTIDX)="<ul>",OUTIDX=OUTIDX+1
        SET TMGIN(OUTIDX)="<li><a href=""HISTORY OF PRESENT ILLNESS (HPI)"">HPI</a>",OUTIDX=OUTIDX+1
          SET TMGIN(OUTIDX)="<ul>",OUTIDX=OUTIDX+1
            SET TMGIN(OUTIDX)="<li><a href=""Social"">Social</a></li>",OUTIDX=OUTIDX+1
            SET TMGIN(OUTIDX)="<li>HTN</li>",OUTIDX=OUTIDX+1
            SET TMGIN(OUTIDX)="<li>DM-2",OUTIDX=OUTIDX+1
              SET TMGIN(OUTIDX)="<ul>",OUTIDX=OUTIDX+1
                SET TMGIN(OUTIDX)="<li>Diabetic Studies table</li>",OUTIDX=OUTIDX+1
              SET TMGIN(OUTIDX)="</ul>",OUTIDX=OUTIDX+1
            SET TMGIN(OUTIDX)="</li>",OUTIDX=OUTIDX+1
          SET TMGIN(OUTIDX)="</ul>",OUTIDX=OUTIDX+1
        SET TMGIN(OUTIDX)="</li>",OUTIDX=OUTIDX+1
        SET TMGIN(OUTIDX)="<li>PMH</li>",OUTIDX=OUTIDX+1
        SET TMGIN(OUTIDX)="<li>ROS",OUTIDX=OUTIDX+1
          SET TMGIN(OUTIDX)="<ul>",OUTIDX=OUTIDX+1
            SET TMGIN(OUTIDX)="<li>Medications</li>",OUTIDX=OUTIDX+1
            SET TMGIN(OUTIDX)="<li>Problem List</li>",OUTIDX=OUTIDX+1
          SET TMGIN(OUTIDX)="</ul>",OUTIDX=OUTIDX+1
        SET TMGIN(OUTIDX)="</li>",OUTIDX=OUTIDX+1  
        SET TMGIN(OUTIDX)="<li><a href=""PHYSICAL EXAM (PE)"">Physical Exam (PE)</a></li>",OUTIDX=OUTIDX+1
        SET TMGIN(OUTIDX)="<li><a href=""[FINAL MEDICATIONS]"">Final Medications table</a></li>",OUTIDX=OUTIDX+1
      SET TMGIN(OUTIDX)="</ul>",OUTIDX=OUTIDX+1
    SET TMGIN(OUTIDX)="</li>",OUTIDX=OUTIDX+1
  SET TMGIN(OUTIDX)="</ul>",OUTIDX=OUTIDX+1
  SET TMGIN(OUTIDX)="",OUTIDX=OUTIDX+1
  SET TMGIN(OUTIDX)="</body>",OUTIDX=OUTIDX+1
  SET TMGIN(OUTIDX)="</html>",OUTIDX=OUTIDX+1
  QUIT
  ;"OLD TEST CODE BELOW, THAT DOESN'T WORK IN IE 6.0
  SET TMGIN(OUTIDX)="<!DOCTYPE html>",OUTIDX=OUTIDX+1
  SET TMGIN(OUTIDX)="<html>",OUTIDX=OUTIDX+1
  SET TMGIN(OUTIDX)="<head>",OUTIDX=OUTIDX+1
  SET TMGIN(OUTIDX)="<meta name=""viewport"" content=""width=device-width, initial-scale=1"">",OUTIDX=OUTIDX+1
  SET TMGIN(OUTIDX)="<style>",OUTIDX=OUTIDX+1
  SET TMGIN(OUTIDX)="ul, #myUL {",OUTIDX=OUTIDX+1
    SET TMGIN(OUTIDX)="list-style-type: none;",OUTIDX=OUTIDX+1
  SET TMGIN(OUTIDX)="}",OUTIDX=OUTIDX+1
  SET TMGIN(OUTIDX)="",OUTIDX=OUTIDX+1
  SET TMGIN(OUTIDX)="#myUL {",OUTIDX=OUTIDX+1
    SET TMGIN(OUTIDX)="margin: 0;",OUTIDX=OUTIDX+1
    SET TMGIN(OUTIDX)="padding: 0;",OUTIDX=OUTIDX+1
  SET TMGIN(OUTIDX)="}",OUTIDX=OUTIDX+1
  SET TMGIN(OUTIDX)="",OUTIDX=OUTIDX+1
  SET TMGIN(OUTIDX)=".caret {",OUTIDX=OUTIDX+1
    SET TMGIN(OUTIDX)="cursor: pointer;",OUTIDX=OUTIDX+1
    SET TMGIN(OUTIDX)="-webkit-user-select: none; /* Safari 3.1+ */",OUTIDX=OUTIDX+1
    SET TMGIN(OUTIDX)="-moz-user-select: none; /* Firefox 2+ */",OUTIDX=OUTIDX+1
    SET TMGIN(OUTIDX)="-ms-user-select: none; /* IE 10+ */",OUTIDX=OUTIDX+1
    SET TMGIN(OUTIDX)="user-select: none;",OUTIDX=OUTIDX+1
  SET TMGIN(OUTIDX)="}",OUTIDX=OUTIDX+1
  SET TMGIN(OUTIDX)="",OUTIDX=OUTIDX+1
  SET TMGIN(OUTIDX)=".caret::before {",OUTIDX=OUTIDX+1
    SET TMGIN(OUTIDX)="content: ""\25B6"";",OUTIDX=OUTIDX+1
    SET TMGIN(OUTIDX)="color: black;",OUTIDX=OUTIDX+1
    SET TMGIN(OUTIDX)="display: inline-block;",OUTIDX=OUTIDX+1
    SET TMGIN(OUTIDX)="margin-right: 6px;",OUTIDX=OUTIDX+1
  SET TMGIN(OUTIDX)="}",OUTIDX=OUTIDX+1
  SET TMGIN(OUTIDX)="",OUTIDX=OUTIDX+1
  SET TMGIN(OUTIDX)=".caret-down::before {",OUTIDX=OUTIDX+1
    SET TMGIN(OUTIDX)="-ms-transform: rotate(90deg); /* IE 9 */",OUTIDX=OUTIDX+1
    SET TMGIN(OUTIDX)="-webkit-transform: rotate(90deg); /* Safari */",OUTIDX=OUTIDX+1
    SET TMGIN(OUTIDX)="transform: rotate(90deg);",OUTIDX=OUTIDX+1  
  SET TMGIN(OUTIDX)="}",OUTIDX=OUTIDX+1
  SET TMGIN(OUTIDX)="",OUTIDX=OUTIDX+1
  SET TMGIN(OUTIDX)=".nested {",OUTIDX=OUTIDX+1
    SET TMGIN(OUTIDX)="display: none;",OUTIDX=OUTIDX+1
  SET TMGIN(OUTIDX)="}",OUTIDX=OUTIDX+1
  SET TMGIN(OUTIDX)="",OUTIDX=OUTIDX+1
  SET TMGIN(OUTIDX)=".active {",OUTIDX=OUTIDX+1
    SET TMGIN(OUTIDX)="display: block;",OUTIDX=OUTIDX+1
  SET TMGIN(OUTIDX)="}",OUTIDX=OUTIDX+1
  SET TMGIN(OUTIDX)="</style>",OUTIDX=OUTIDX+1
  SET TMGIN(OUTIDX)="</head>",OUTIDX=OUTIDX+1
  SET TMGIN(OUTIDX)="<body>",OUTIDX=OUTIDX+1
  SET TMGIN(OUTIDX)="",OUTIDX=OUTIDX+1
  SET TMGIN(OUTIDX)="<h2>NOTE CONTENTS TREE VIEW</h2>",OUTIDX=OUTIDX+1
  SET TMGIN(OUTIDX)="<ul id=""myUL"">",OUTIDX=OUTIDX+1
    SET TMGIN(OUTIDX)="<li><span class=""caret""></span><span>Note Contents</span>",OUTIDX=OUTIDX+1
      SET TMGIN(OUTIDX)="<ul class=""nested"">",OUTIDX=OUTIDX+1
        SET TMGIN(OUTIDX)="<li><span class=""caret""></span><a href=""HISTORY OF PRESENT ILLNESS (HPI):"">HPI</a>",OUTIDX=OUTIDX+1
          SET TMGIN(OUTIDX)="<ul class=""nested"">",OUTIDX=OUTIDX+1
            SET TMGIN(OUTIDX)="<li>Social</li>",OUTIDX=OUTIDX+1
            SET TMGIN(OUTIDX)="<li>HTN</li>",OUTIDX=OUTIDX+1
            SET TMGIN(OUTIDX)="<li><span class=""caret""></span>DM-2",OUTIDX=OUTIDX+1
              SET TMGIN(OUTIDX)="<ul class=""nested"">",OUTIDX=OUTIDX+1
                SET TMGIN(OUTIDX)="<li>Diabetic Studies table</li>",OUTIDX=OUTIDX+1
              SET TMGIN(OUTIDX)="</ul>",OUTIDX=OUTIDX+1
            SET TMGIN(OUTIDX)="</li>",OUTIDX=OUTIDX+1
          SET TMGIN(OUTIDX)="</ul>",OUTIDX=OUTIDX+1
        SET TMGIN(OUTIDX)="</li>",OUTIDX=OUTIDX+1
        SET TMGIN(OUTIDX)="<li>PMH</li>",OUTIDX=OUTIDX+1
        SET TMGIN(OUTIDX)="<li><span class=""caret""></span>ROS",OUTIDX=OUTIDX+1
          SET TMGIN(OUTIDX)="<ul class=""nested"">",OUTIDX=OUTIDX+1
            SET TMGIN(OUTIDX)="<li>Medications</li>",OUTIDX=OUTIDX+1
            SET TMGIN(OUTIDX)="<li>Problem List</li>",OUTIDX=OUTIDX+1
          SET TMGIN(OUTIDX)="</ul>",OUTIDX=OUTIDX+1
        SET TMGIN(OUTIDX)="</li>",OUTIDX=OUTIDX+1  
        SET TMGIN(OUTIDX)="<li><a href=""<B>PHYSICAL EXAM (PE):</B>:"">Physical Exam (PE)</a></li>",OUTIDX=OUTIDX+1
      SET TMGIN(OUTIDX)="</ul>",OUTIDX=OUTIDX+1
    SET TMGIN(OUTIDX)="</li>",OUTIDX=OUTIDX+1
  SET TMGIN(OUTIDX)="</ul>",OUTIDX=OUTIDX+1
  SET TMGIN(OUTIDX)="",OUTIDX=OUTIDX+1
  SET TMGIN(OUTIDX)="<script>",OUTIDX=OUTIDX+1
  SET TMGIN(OUTIDX)="var carets = document.getElementsByClassName(""caret"");",OUTIDX=OUTIDX+1
  SET TMGIN(OUTIDX)="var i;",OUTIDX=OUTIDX+1
  SET TMGIN(OUTIDX)="",OUTIDX=OUTIDX+1
  SET TMGIN(OUTIDX)="for (i = 0; i < carets.length; i++) {",OUTIDX=OUTIDX+1
    SET TMGIN(OUTIDX)="carets[i].addEventListener(""click"", function() {",OUTIDX=OUTIDX+1
      SET TMGIN(OUTIDX)="this.parentElement.querySelector("".nested"").classList.toggle(""active"");",OUTIDX=OUTIDX+1
      SET TMGIN(OUTIDX)="this.classList.toggle(""caret-down"");",OUTIDX=OUTIDX+1
    SET TMGIN(OUTIDX)="});",OUTIDX=OUTIDX+1
  SET TMGIN(OUTIDX)="}",OUTIDX=OUTIDX+1
  SET TMGIN(OUTIDX)="</script>",OUTIDX=OUTIDX+1
  SET TMGIN(OUTIDX)="",OUTIDX=OUTIDX+1
  SET TMGIN(OUTIDX)="</body>",OUTIDX=OUTIDX+1
  SET TMGIN(OUTIDX)="</html>",OUTIDX=OUTIDX+1
  QUIT
            ;"  
OLDTOCPARSE(TMGOUT,OUTIDX,TMGIN)
  ;
  NEW TMGHPI SET TMGHPI=""    
  ;"CONVERT ENTIRE NOTE INTO LONG STRING (TMGHPI)
  SET IDX=0 FOR  SET IDX=$ORDER(TMGIN("TEXT",IDX)) QUIT:IDX'>0  DO
  . SET TMGHPI=TMGHPI_$GET(TMGIN("TEXT",IDX))
  IF TMGHPI="" SET TMGRESULT="-1^No text for not found for processing." QUIT         
  NEW SECTIONARR,TOPICTAG
  SET SECTIONARR("HISTORY OF PRESENT ILLNESS (HPI):")=""
  SET SECTIONARR("PAST MEDICAL HISTORY (PMH)")=""
  SET SECTIONARR("PHYSICAL EXAM (PE)")=""
  SET SECTIONARR("REVIEW OF SYSTEMS")=""
  SET SECTIONARR("ASSESSMENT &amp; PLAN")=""
  SET SECTIONARR("FOLLOW UP APPT:")=""
  NEW STARTDIV,ENDDIV SET (STARTDIV,ENDDIV)=""
  ;"
  SET TMGHPI=$$UPTAGS^TMGHTM2(TMGHPI)  ;"force all tags to UPPER CASE
  ;"Remove/replace unwanted tags / strings from note  
  DO RPTAGS^TMGHTM1(.TMGHPI,"<BR />","<BR>")
  DO RPTAGS^TMGHTM1(.TMGHPI,"<P />","<P>")
  DO RMTAGS^TMGHTM1(.TMGHPI,"=== HPI ISSUES BELOW WERE NOT ADDRESSED TODAY ===")
  DO RMTAGS^TMGHTM1(.TMGHPI,"--&nbsp;[FOLLOWUP&nbsp;ITEMS]&nbsp;---------")
  ;"DO RMTAGS^TMGHTM1(.TMGHPI,"-- [FOLLOWUP ITEMS] ---------")
  DO RPTAGS^TMGHTM1(.TMGHPI,"<LI>  <P>","<LI> ")
  DO RPTAGS^TMGHTM1(.TMGHPI,"[group ","[GROUP ")  ;"force group tags to be ucase 11/13/18
  DO RPTAGS^TMGHTM1(.TMGHPI,"[Group ","[GROUP ")
  DO RMTAGS^TMGHTM1(.TMGHPI,"<I>")   ;"//kt should have been already removed via DOM processing
  DO RMTAGS^TMGHTM1(.TMGHPI,"<EM>")  ;"//kt should have been already removed via DOM processing
  DO RMTAGS^TMGHTM1(.TMGHPI,"</I>")  ;"//kt should have been already removed via DOM processing
  DO RMTAGS^TMGHTM1(.TMGHPI,"</EM>") ;"//kt should have been already removed via DOM processing         
  ;"                           
  ;"Parse Items
  NEW TABLES,SECTION SET IDX=1 
  NEW OUTSIDEHPI SET OUTSIDEHPI=1
  NEW INSIDESECTION SET INSIDESECTION=0
  NEW INSIDETOPIC SET INSIDETOPIC=0
  NEW TOPICOL SET TOPICOL=0
  NEW DELIMITER SET DELIMITER=$$NEXTCH^TMGSTUT3(TMGHPI,0,"<LI>","*")
  ;"If the delimiter is *, then we will replace any <LI>'s to *
  ;"IF DELIMITER="*" SET TMGHPI=$$REPLSTR^TMGSTUT3(TMGHPI,"<LI>","*")
  ;"
  ;"NEW INSIDE
  NEW DELIMITER
  NEW TABLEARR
  NEW TOCARR,CURSECTION   ;"CHANGING THE WAY WE SAVE OFF THE DATA. INSTEAD OF SAVING THE DATA AS WE GO, I AM GOING TO STORE THE DATA LIKE THIS: TOCARR(SECTION,TITLE) AND THEN HAVE ONE FUNCTION THAT SETS THE LIST AFTERWARDS
  SET CURSECTION=""
  NEW HPIARR
  NEW HPIALPHA SET HPIALPHA=1   ;"CHANGE THIS (PER USER OR SETTING) IF YOU DON'T WANT ALPHABETICAL
  FOR  QUIT:TMGHPI=""  DO
  . ;"ADD FOLLOWUP AT BOTTOM TO THE LIST
  . IF OUTSIDEHPI DO
  . . SET DELIMITER=$$NEXTCH^TMGSTUT3(TMGHPI,0,"-- [","HISTORY OF PRESENT ILLNESS (HPI):","PAST MEDICAL HISTORY (PMH)","PHYSICAL EXAM (PE)","REVIEW OF SYSTEMS","ASSESSMENT &amp; PLAN","FOLLOW UP APPT:") 
  . ELSE  DO
  . . SET DELIMITER=$$NEXTCH^TMGSTUT3(TMGHPI,0,"*","<LI>","-- [","HISTORY OF PRESENT ILLNESS (HPI):","PAST MEDICAL HISTORY (PMH)","PHYSICAL EXAM (PE)","REVIEW OF SYSTEMS","ASSESSMENT &amp; PLAN","FOLLOW UP APPT:")
  . NEW TOPIC
  . IF DELIMITER="-- [" DO
  . . ;"OLD LINE!! IF INSIDESECTION=0 SET TMGOUT(OUTIDX)="<ul>",OUTIDX=OUTIDX+1,INSIDESECTION=1
  . . ;"OLD LINE!! IF (INSIDETOPIC=1)&(TOPICOL=0) SET TMGOUT(OUTIDX)="<ul>",OUTIDX=OUTIDX+1,TOPICOL=1
  . . SET TOPIC=$P(TMGHPI,DELIMITER,2)
  . . SET TOPIC=$P(TOPIC,"] --",1)
  . . SET TMGHPI=$P(TMGHPI,"] --",2,999)
  . . ;"OLD LINE!! SET TMGOUT(OUTIDX)="<li><a href=""["_TOPIC_"]"">"_TOPIC_" table</a></li>",OUTIDX=OUTIDX+1
  . . ;"SET TABLEARR("<li><a href=""["_TOPIC_"]"">"_TOPIC_" table</a></li>")=""
  . . SET TOCARR("ZTABLES",TOPIC)=""
  . ELSE  IF $D(SECTIONARR(DELIMITER)) DO
  . . ;"IF INSIDESECTION=1 SET TMGOUT(OUTIDX)="</ul>",OUTIDX=OUTIDX+1,INSIDESECTION=0
  . . ;"IF TOPICOL=1 SET TMGOUT(OUTIDX)="</ul>",OUTIDX=OUTIDX+1
  . . IF DELIMITER["HPI" DO
  . . . SET OUTSIDEHPI=0
  . . ELSE  DO
  . . . SET OUTSIDEHPI=1
  . . . ;"IF $D(HPIARR) DO
  . . . ;". DO INSRTHPI(.TMGOUT,.OUTIDX,.HPIARR)
  . . . ;". KILL HPIARR
  . . ;"SET TMGOUT(OUTIDX)="<li><a href="""_DELIMITER_""">"_DELIMITER_"</a></li>",OUTIDX=OUTIDX+1
  . . IF DELIMITER["HPI" DO
  . . . SET CURSECTION="A"_DELIMITER
  . . ELSE  DO
  . . . SET CURSECTION=DELIMITER
  . . SET TOCARR(CURSECTION)=""
  . . SET TMGHPI=$P(TMGHPI,DELIMITER,2,999)
  . . SET INSIDETOPIC=0
  . ELSE  DO
  . . ;"IF INSIDESECTION=0 SET TMGOUT(OUTIDX)="<ul>",OUTIDX=OUTIDX+1,INSIDESECTION=1
  . . ;"IF TOPICOL=1 SET TMGOUT(OUTIDX)="</ul>",OUTIDX=OUTIDX+1
  . . SET TMGHPI=$PIECE(TMGHPI,DELIMITER,2,999)
  . . NEW NEXTDEL
  . . IF OUTSIDEHPI DO
  . . . SET NEXTDEL=$$NEXTCH^TMGSTUT3(TMGHPI,0,"-- [","HISTORY OF PRESENT ILLNESS (HPI):","PAST MEDICAL HISTORY (PMH)","PHYSICAL EXAM (PE)","REVIEW OF SYSTEMS","ASSESSMENT &amp; PLAN","FOLLOW UP APPT:") 
  . . ELSE  DO
  . . . SET NEXTDEL=$$NEXTCH^TMGSTUT3(TMGHPI,0,"*","<LI>","-- [","HISTORY OF PRESENT ILLNESS (HPI):","PAST MEDICAL HISTORY (PMH)","PHYSICAL EXAM (PE)","REVIEW OF SYSTEMS","ASSESSMENT &amp; PLAN","FOLLOW UP APPT:")
  . . NEW SECTION SET SECTION=$PIECE(TMGHPI,NEXTDEL,1)
  . . NEW TITLE,TEXTARR DO SPLITTL^TMGTIUP2(SECTION,.TITLE,.TEXTARR,.TABLES,.OPTION) ;"Parse to a title of section, and parts
  . . DO RMTAGS^TMGHTM1(.TITLE,$C(13,10,13,10))  ;"//kt should have been already removed via DOM processing
  . . DO RMTAGS^TMGHTM1(.TITLE,$C(13,10))  ;"//kt should have been already removed via DOM processing
  . . NEW TRIMTITLE SET TRIMTITLE=$$TRIM^XLFSTR(TITLE)
  . . ;"SET TMGHPI=$P(TMGHPI,DELIMITER,2,999)
  . . SET INSIDETOPIC=1,TOPICOL=0
  . . IF CURSECTION="" SET CURSECTION="ERROR SECTION"
  . . SET TOCARR(CURSECTION,TITLE)=""
  . . ;"IF (HPIALPHA=1)&(OUTSIDEHPI=0) DO  QUIT
  . . ;". IF TRIMTITLE'="" SET HPIARR(TITLE)=""
  . . ;"IF TRIMTITLE'="" SET TMGOUT(OUTIDX)="<li><a href="""_TITLE_":"">"_TITLE_"</a></li>",OUTIDX=OUTIDX+1
  ;"
  NEW SECTION,TITLE SET SECTION=""
  FOR  SET SECTION=$O(TOCARR(SECTION)) QUIT:SECTION=""  DO
  . IF SECTION="ZTABLES" DO
  . . SET TMGOUT(OUTIDX)="<ul>",OUTIDX=OUTIDX+1
  . . SET TMGOUT(OUTIDX)="<li>TABLES</li>",OUTIDX=OUTIDX+1
  . ELSE  IF SECTION["HPI" DO
  . . SET TMGOUT(OUTIDX)="<ul>",OUTIDX=OUTIDX+1
  . . SET TMGOUT(OUTIDX)="<li><a href=""HISTORY OF PRESENT ILLNESS (HPI):"">HISTORY OF PRESENT ILLNESS (HPI):</a></li>",OUTIDX=OUTIDX+1
  . ELSE  DO
  . . SET TMGOUT(OUTIDX)="<ul>",OUTIDX=OUTIDX+1
  . . SET TMGOUT(OUTIDX)="<li><a href="""_SECTION_""">"_SECTION_"</a></li>",OUTIDX=OUTIDX+1
  . SET TITLE=""
  . NEW SUBITEMS SET SUBITEMS=0
  . FOR  SET TITLE=$O(TOCARR(SECTION,TITLE)) QUIT:TITLE=""  DO
  . . IF SUBITEMS=0 DO
  . . . SET TMGOUT(OUTIDX)="<ul>",OUTIDX=OUTIDX+1
  . . . SET SUBITEMS=1
  . . IF SECTION="ZTABLES" DO
  . . . SET TMGOUT(OUTIDX)="<li><a href=""["_TITLE_"]"">"_TITLE_" table</a></li>")="",OUTIDX=OUTIDX+1
  . . ELSE  DO
  . . . SET TMGOUT(OUTIDX)="<li><a href="""_TITLE_":"">"_TITLE_"</a></li>",OUTIDX=OUTIDX+1
  . IF SUBITEMS=1 SET TMGOUT(OUTIDX)="</ul>",OUTIDX=OUTIDX+1
  . SET TMGOUT(OUTIDX)="</ul>",OUTIDX=OUTIDX+1
  SET TMGOUT(OUTIDX)="DONE DUMMY!",OUTIDX=OUTIDX+1
  ;"
  QUIT
  IF INSIDESECTION=1 SET TMGOUT(OUTIDX)="</ul>",OUTIDX=OUTIDX+1
  IF $D(TABLEARR) DO
  . SET TMGOUT(OUTIDX)="<li>TABLES</li><ul>",OUTIDX=OUTIDX+1
  . NEW TABLELINE SET TABLELINE=""
  . FOR  SET TABLELINE=$O(TABLEARR(TABLELINE)) QUIT:TABLELINE=""  DO
  . . SET TMGOUT(OUTIDX)=TABLELINE,OUTIDX=OUTIDX+1
  . SET TMGOUT(OUTIDX)="</ul>",OUTIDX=OUTIDX+1
  QUIT            